### ISSUE TITLE
AttributeError: Connector instance has no attribute 'logger'

### ISSUE THREAD

**Issue by xil3so** [Donearm/PyImagedownloader#2]
After fixing few random issues and preparing host-readable config file I decided to try it with random URL. Unfortunately it failed beyond my understanding:

 $ /usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.pyc http://imgchili.net/album/...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.py", line 428, in <module>
    download_url(url, basedir, options.embed, options.poster)
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/pyimagedownloader.py", line 312, in download_url
    connector = http_connector.Connector()
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/http_connector.py", line 52, in **init**
    self.opener = self.threadsafe_opener()
  File "/usr/local/lib/python2.7/dist-packages/PyImagedownloader-1.6-py2.7.egg/pyimagedownloader/http_connector.py", line 60, in threadsafe_opener
    self.logger.setLevel(logging.DEBUG)
AttributeError: Connector instance has no attribute 'logger'

Exactly the same with generic URL, e.g. ' http://ifconfig.me/'.

**Comment by Donearm** [comment]
Closing this as "wontfix" as the project is in unmaintained state (not enough time to update it as much as it'd need to be working again and/or lost interest in it). Feel free to open a PR.

In this specific case, as far as I remember imgchili changed from time to time the html of the page where the image is shown. Therefore, there needs to check the page source to discover the new tags/ids to look for.
